### ISSUE TITLE
Token-based authentication and Network Error: Bad Request(400) errors

### ISSUE THREAD

**Issue by khalid-gh** [jorgedlcruz/veeam-backup-gcp-grafana#1]
Hello Jorge, great work on this dashboard. I have a few questions regarding some issues I'm facing.

Firstly, is there the possibility of replacing _veeamPassword="YOURVEEAMBACKUPPASS"_ with authorization/refresh tokens as opposed to a plain text password in the script so as to be more secure?

Secondly, when I run the script, I get the following response:

Writing veeam_gcp_sessions to InfluxDB
**HTTP/1.1 204 No Content**
X-Influxdb-Build: OSS
X-Influxdb-Version: 2.1.1
Date: Wed, 19 Jan 2022 19:51:17 GMT

When I subsequently checked InfluxDB, the data appears to be there. However, when I attempt to view it in the Grafana dashboard (after configuring InfluxDB as a data source, and importing the dashboard with the ID), I'm met with the following error on every panel:

**Error updating options: Network Error: Bad Request(400)**

Any assistance you can provide is greatly appreciated

![grafana-dashboard](https://user-images.githubusercontent.com/88779845/150207212-b8b4f2ea-39b3-4149-923d-5c20d446899c.jpeg)
.

**Comment by jorgedlcruz** [comment]
Hello,
Will give it a try to see if we can make more secure the whole auth thing. You can always have a dedicated user for this purpose, and of course secure at the network layer, meaning opening the API TCP Port to the InfluxDB Server alone, not ideal I know.

By the message you are sharing, the Script is sending the data correctly to InfluxDB, which is nice! However, your Grafana config of the InfluxDB Datasource is not right.

You can give it a try, if you go to the Explore option, on Grafana. Let me know. Thanks for trying it.

**Comment by khalid-gh** [comment]
Thanks for getting back to me. I've checked the configuration of the InfluxDB data source and it seems to be successful, however I still get the same errors. In the Explore option, I get the following error when trying to run a query: **InfluxDB Error: database not found**

![data-source](https://user-images.githubusercontent.com/88779845/150413861-7c2f4860-bb76-435d-bb85-c62333bddcd2.jpeg)

**Comment by jorgedlcruz** [comment]
Hello,
Would you mind to show me a bit more to the top, the type of InfluxDB you
are configuring.

And you said that in Chronograf, the InfluxDB webui, you can see data right?

Thanks!

**Comment by khalid-gh** [comment]
Hello,

I've now managed to successfully configure the connection between InfluxDB and Grafana, and can now see the data visualised in the dashboard. However, there are two panels with no data, and they happen to be the panels which I'm most interested in.

That leads me on to my next question, which is: is there any way I can set up an alerting rule on those panels (specifically the **Job Historical Information** panel), so that I can send those alerts to Slack when a backup job fails?

Thanks!

![job-history](https://user-images.githubusercontent.com/88779845/150567152-e2ed87ae-9e30-4c18-90a2-7059803abad2.jpeg)

**Comment by jorgedlcruz** [comment]
Hello,
Did you have any errors once you run the script? Take a look at those
panels, and look at the query, then look inside influxdb and see if you
have data.

Yes, you can create alerts on the queries. Will create a blog post about it

**Comment by khalid-gh** [comment]
Hello, 

I've checked and I still get the same response as before:

Writing veeam_gcp_sessions to InfluxDB
HTTP/1.1 204 No Content
X-Influxdb-Build: OSS
X-Influxdb-Version: 2.1.1
Date: Fri, 21 Jan 2022 17:14:52 GMT

Both the empty panels are measuring **veeam_gcp_sessions** and unfortunately in InfluxDB, the response is **No values found in the current time range**

Also eagerly looking forward to that blog post as I need to receive alerts for failed backup jobs.

Thanks

![influxdb](https://user-images.githubusercontent.com/88779845/150571806-daf2cd7b-4fd7-45c0-80ca-55347368a352.jpeg)

**Comment by jorgedlcruz** [comment]
Can you perhaps change the top time in Grafana to show last 7 days for
example?

**Comment by khalid-gh** [comment]
I've tried all the different time ranges in Grafana and still no luck. Data is available for the other measurements in InfluxDB to present in Grafana, but I'm not sure why there is no data available for **veeam_gcp_sessions** in InfluxDB.

**Comment by jorgedlcruz** [comment]
Have you been running jobs right? The script has a commented echo on every
section, if you enable it, and run it, you shall see the output on the
console, please enable it for the sessions part, run it and paste some of
the result :)
